name: Upload website to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on:
    steps:
    - uses:
    - uses:
    with:
      args:
    env:
      AWS_S3_BUCKET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
      SOURCE_DIR: